import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const KEY='tile-planner-projects-v01';const tg=()=>window.Telegram?.WebApp;
function App(){const[screen,setScreen]=useState('home');const[projects,setProjects]=useState(()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}});const[name,setName]=useState('');const[room,setRoom]=useState({name:'Санузел',length:'3000',width:'2500',height:'2700'});useEffect(()=>{tg()?.ready?.();tg()?.expand?.()},[]);useEffect(()=>localStorage.setItem(KEY,JSON.stringify(projects)),[projects]);
function create(){const p={id:Date.now(),name:name.trim()||'Новый проект',rooms:[]};setProjects(x=>[p,...x]);setName('');setScreen('room')}
function addRoom(){const l=+room.length,w=+room.width,h=+room.height;if(!l||!w||!h)return;const r={id:Date.now(),name:room.name.trim()||'Комната',length:l,width:w,height:h,area:(l*w/1e6).toFixed(2)};setProjects(x=>{const y=[...x];if(!y[0])return y;y[0]={...y[0],rooms:[...y[0].rooms,r]};return y});setScreen('home')}
if(screen==='home')return <main className="app"><header><div><div className="eyebrow">TILE PLANNER</div><h1>Мои проекты</h1></div><div className="logo">TP</div></header><div className="home-layout"><div><section className="hero"><div><span className="pill">MVP 0.1</span><h2>Планировка,<br/>плитка и раскрой.</h2><p>Собираем проект помещения прямо в Telegram.</p></div><div className="grid">{Array.from({length:12},(_,i)=><i key={i}/>)}</div></section><button className="primary" onClick={()=>setScreen('new')}>＋ Новый проект</button></div><section className="section"><div className="section-title">Проекты <span>{projects.length}</span></div>{!projects.length?<div className="empty"><div className="empty-icon">□</div><strong>Пока проектов нет</strong><p>Создай первый проект — дальше добавим комнаты и редактор планировки.</p></div>:<div className="list">{projects.map(p=><div className="card" key={p.id}><div className="icon">⌂</div><div><strong>{p.name}</strong><span>{p.rooms.length} помещений</span></div><b>›</b></div>)}</div>}</section></div></main>;
if(screen==='new')return <main className="app"><button className="back" onClick={()=>setScreen('home')}>‹ Назад</button><div className="head"><div className="eyebrow">ШАГ 1</div><h1>Новый проект</h1><p>Сначала дадим проекту название.</p></div><label>Название проекта</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Например: Квартира Петровых"/><button className="primary bottom" onClick={create}>Создать проект</button></main>;
return <main className="app"><button className="back" onClick={()=>setScreen('home')}>‹ Назад</button><div className="head"><div className="eyebrow">ШАГ 2</div><h1>Добавить комнату</h1><p>Первая версия поддерживает простую прямоугольную комнату.</p></div><label>Название</label><input value={room.name} onChange={e=>setRoom({...room,name:e.target.value})}/><div className="fields"><div><label>Длина, мм</label><input inputMode="numeric" value={room.length} onChange={e=>setRoom({...room,length:e.target.value.replace(/\D/g,'')})}/></div><div><label>Ширина, мм</label><input inputMode="numeric" value={room.width} onChange={e=>setRoom({...room,width:e.target.value.replace(/\D/g,'')})}/></div></div><label>Высота, мм</label><input inputMode="numeric" value={room.height} onChange={e=>setRoom({...room,height:e.target.value.replace(/\D/g,'')})}/><div className="preview"><div className="room"><div className="rect"><span>{room.length||0} мм</span><b>{room.width||0} мм</b></div></div><div className="stats"><div><small>Площадь пола</small><strong>{((+room.length||0)*(+room.width||0)/1e6).toFixed(2)} м²</strong></div><div><small>Объём</small><strong>{((+room.length||0)*(+room.width||0)*(+room.height||0)/1e9).toFixed(2)} м³</strong></div></div></div><button className="primary bottom" onClick={addRoom}>Добавить комнату</button></main>}
createRoot(document.getElementById('root')).render(<App/>);
