
import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
const KEY='tile-planner-projects-v01';
const tg=()=>window.Telegram?.WebApp;
function App(){const[screen,setScreen]=useState('home');const[projects,setProjects]=useState(()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}});const[name,setName]=useState('');const[room,setRoom]=useState({name:'Санузел',length:'3000',width:'2500',height:'2700'});useEffect(()=>{tg()?.ready?.();tg()?.expand?.()},[]);useEffect(()=>localStorage.setItem(KEY,JSON.stringify(projects)),[projects]);
function create(){const p={id:Date.now(),name:name.trim()||'Новый проект',rooms:[]};setProjects(x=>[p,...x]);setName('');setScreen('room')}
function addRoom(){const l=+room.length,w=+room.width,h=+room.height;if(!l||!w||!h)return;const r={id:Date.now(),name:room.name.trim()||'Комната',length:l,width:w,height:h,area:(l*w/1e6).toFixed(2)};setProjects(x=>{const y=[...x];if(!y[0])return y;y[0]={...y[0],rooms:[...y[0].rooms,r]};return y});setScreen('home')}
return <main><header><h1>Tile Planner</h1><span>MVP 0.2</span></header>{screen==='home'?<section><div className="hero"><h2>Планировщик помещений</h2><p>Создавай проекты, добавляй комнаты и считай площадь.</p></div><div className="card"><h3>Новый проект</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Название проекта"/><button onClick={create}>Создать проект</button></div>{projects.length>0&&<div className="card"><h3>Проекты</h3>{projects.map(p=><div className="project" key={p.id}><strong>{p.name}</strong><small>{p.rooms.length} помещений</small></div>)}</div>}</section>:<section><button className="back" onClick={()=>setScreen('home')}>← Назад</button><div className="card"><h2>Добавить помещение</h2><label>Название<input value={room.name} onChange={e=>setRoom({...room,name:e.target.value})}/></label><div className="grid"><label>Длина, мм<input inputMode="numeric" value={room.length} onChange={e=>setRoom({...room,length:e.target.value})}/></label><label>Ширина, мм<input inputMode="numeric" value={room.width} onChange={e=>setRoom({...room,width:e.target.value})}/></label><label>Высота, мм<input inputMode="numeric" value={room.height} onChange={e=>setRoom({...room,height:e.target.value})}/></label></div><div className="stats"><b>{(+room.length*+room.width/1e6||0).toFixed(2)} м²</b><span>Площадь пола</span></div><button onClick={addRoom}>Добавить помещение</button></div></section>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
